app = "traccar-railway"
primary_region = "nrt"

[build]
  image = "traccar/traccar:latest"

[env]
  TZ = "Asia/Tokyo"

# ← 永続化。あとでボリュームを作ってマウントします
[mounts]
  source = "traccar_data"
  destination = "/opt/traccar"

# --- Traccar Web UI (内部 8082) を 外部 80/443 で公開 ---
[[services]]
  internal_port = 8082
  protocol = "tcp"
  processes = ["app"]
  [[services.ports]]
    port = 80
    handlers = ["http"]
  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

# --- デバイス受信用 Osmand/HTTP (内部 5055) を 外部 5055 で公開 ---
[[services]]
  internal_port = 5055
  protocol = "tcp"
  processes = ["app"]
  [[services.ports]]
    port = 5055
